<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form method="post" id="formAssinante" class="form-horizontal" role="form">
                <input type="hidden" name="id" value="<?php echo $this->view->usuario['id'] ?>">
                <div  class="form-cadastro">
                    <h4><i class="glyphicon glyphicon-lock"></i> Área do assinante <a class="link-secundario link-p" href="/logout">Sair</a></h4>
                    <hr>
                    <p>Olá <b><?php echo $this->view->usuario['nome'] ?></b>. Bom dia!  <span class="observacao-usuarios">*Campos obrigatórios</span></p>
                    <p>Altere e/ou confirme seu dados:</p>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nome<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <input type="text" name="nome" class="form-control" placeholder="Nome" value="<?php echo $this->view->usuario['nome'] ?>"
                                   data-bv-notempty="true"
                                   data-bv-notempty-message="Por favor informe o nome!"
                                />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                            <input type="text" name="email" class="form-control" placeholder="E-mail" value="<?php echo $this->view->usuario['email'] ?>"
                                   data-bv-notempty="true"
                                   data-bv-notempty-message="Por favor informe o email!"
                                   data-bv-emailaddress="true"
                                   data-bv-emailaddress-message="Informe um email válido!"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Celular</label>
                        <div class="col-sm-5">
                            <input type="text" name="celular" class="form-control" placeholder="Celular" value="<?php echo $this->view->usuario['celular'] ?>"
                                   data-bv-notempty="true"
                                   data-bv-notempty-message="Por favor informe o celular!"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Mailing</label>
                        <div class="checkbox col-sm-5 sem-padding">
                            <?php if($this->view->usuario['mailing'] == 1){ ?>
                                <input type="checkbox" name="mailing" value="1" checked> Receber notícias
                            <?php } else {?>
                                <input type="checkbox" name="mailing" value="1"> Receber notícias
                            <?php } ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12" style="padding-right:20px;">

                            <button type="submit" class="btn btn-principal">Confirmar</button>
                            <a class="btn btn-default" href="#">Restaurar</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>