<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-cadastro">
                <h4><i class="glyphicon glyphicon-user"></i> Novo Cadastro </h4>
                <hr>
                <h4>Quase lá...</h4>
                <h5>Verifique sua conta de e-mail</h5>
                <p>Para completar seu cadastro nós precisamos verificar seu e-mail.</p>
                <p>Uma mensagem foi enviada para: <a href="#"><?php echo $this->view->usuario['email']?></a> </p>
                <p>Verifique sua caixa postal e clique no link de confirmação para efetuar a liberação do seu cadastro.</p>
                <p><button class="btn btn-default" style="float: left;margin-bottom: 30px;">Reenviar link de confirmação</button></p>
                <div class="row">
                    <div class="col-md-12">
                        <p><a href="/" class="link-secundario"><i class="glyphicon glyphicon-triangle-left"></i> Retornar à tela de login</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>