<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-cadastro">
                <h4><i class="glyphicon glyphicon-lock"></i> Esqueci senha </h4>
                <hr>
                <p>Um e-mail contendo um link para alterar sua senha foi enviado para <a href="#"><?php echo $this->view->usuario['email'] ?></a></p>
                <div class="row">
                    <div class="col-md-12">
                        <p><a href="/" class="link-secundario"><i class="glyphicon glyphicon-triangle-left"></i> Voltar</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>