
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form method="post" id="formEsqueceu" role="form"
                  data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
                  data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
                  data-bv-feedbackicons-validating="glyphicon glyphicon-refresh">
                <div class="form-cadastro">
                    <h4><i class="glyphicon glyphicon-lock"></i> Esqueci senha </h4>
                    <hr>
                    <?php if($this->view->erro == true){ ?>
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Erro!</strong> Email inexistente em nosso banco de dados!
                        </div>
                    <?php } ?>

                        <div class="form-group" style="text-align: left !important;">
                            <label>Localize os dados de sua conta:</label>
                            <input type="email" name="email" class="form-control" placeholder="Informe seu e-mail ou login"
                                   data-bv-notempty="true"
                                   data-bv-notempty-message="Por favor informe o email!"
                                   data-bv-emailaddress="true"
                                    data-bv-emailaddress-message="Informe um email válido!">
                        </div>

                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-principal" style="margin-right: 0;">Buscar</button>
                            <p><a href="/" class="link-secundario"><i class="glyphicon glyphicon-triangle-left"></i> Retornar ao login</a></p>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>