version: '2'
services:
    php:
      build: .
      ports:
       - "9022:9000"
      links:
        - mysql
      volumes:
       - "./:/var/www/html/"
    nginx:
      image: nginx
      links:
       - php:fpm
      ports:
       - "8081:80"
      volumes:
       - "./:/var/www/html"
       - "./conf/nginx/conf.d/:/etc/nginx/conf.d/"
       - "./log/nginx/:/var/log/nginx/"
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: php123
            MYSQL_DATABASE: teste_php
        ports:
            - "3307:3306"
        volumes:
            - "./mysql:/var/lib/mysql"
            - "./mysql-data/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
        command: mysqld --sql_mode=""
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - "8082:80"