<h2>Artigos</h2>
<?php if($_GET['editaok'] == 1){ ?>
    <div class="alert alert-success-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Sucesso!</strong> Edição realizada com sucesso!.
    </div>
<? } ?>
<a href="/artigo/novo" class="btn-large btn pull-right btn-primary" id="adicionar">Adicionar</a>

<br />
<br />
<br />
<?php //print_r($this->view->objetos);die; ?>
<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th width="10%" align="center">Ação</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->view->objetos as $registro): ?>
        <tr>
            <td align="left"><?= $registro['titulo']; ?></td>
            <td align="left"><?= $registro['texto']; ?></td>
            <td>
                <a href="/artigo/edit?id=<?=$registro['id'];?>">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                &nbsp;
                <a href="/artigo/delete?id=<?=$registro['id'];?>">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>