<?php
if (isset($_GET['editok'])){
    if($_GET['editok'] == 1){
?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Sucesso!</strong> Edição realizada com sucesso!.
        </div>
<?php }} ?>

<?php
if (isset($_GET['saveok'])){
    if($_GET['saveok'] == 1){
        ?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Sucesso!</strong> Artigo Inserido com sucesso!.
        </div>
<?php }} ?>

<?php
if (isset($_GET['deleteok'])){
    if($_GET['deleteok'] == 1){
        ?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Sucesso!</strong> Artigo Excluido com sucesso!.
        </div>
<?php }} ?>
<h2>Artigos</h2>

<a href="/artigo/novo" class="btn-large btn pull-right btn-primary" id="adicionar" data-toggle="modal" data-target="#adicionarModal">Adicionar</a>

<br />
<br />
<br />

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th width="10%" align="center">Ação</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->view->objetos as $registro): ?>
        <tr>
            <td align="left"><?= $registro['titulo']; ?></td>
            <td align="left"><?= $registro['texto']; ?></td>
            <td>
                <a href="/artigo/edit?id=<?=$registro['id'];?>" data-toggle="modal" data-target="#editarModal-<?=$registro['id'];?>">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                &nbsp;
                <a href="#" data-toggle="modal" data-target="#excluirModal-<?=$registro['id'];?>">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>


        <!-- Excluir Modal -->
        <div class="modal fade" id="excluirModal-<?=$registro['id'];?>" tabindex="-1" role="dialog" aria-labelledby="excluirModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="excluirModalLabel">Confirmação de Exclusão</h4>
                    </div>
                    <div class="modal-body">
                        <h2>tem certeza que deseja excluir o artigo "<?= $registro['titulo']; ?>"?</h2>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        <a href="/artigo/delete?id=<?=$registro['id'];?>" class="btn btn-danger">Excluir</a>
                    </div>

                </div>
            </div>
        </div>

        <!-- Editar Modal -->
        <div class="modal fade" id="editarModal-<?=$registro['id'];?>" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="editarModalLabel">Editar Artigo</h4>
                    </div>

                </div>
            </div>
        </div>

    <?php endforeach; ?>
    </tbody>
</table>

<!-- Adicionar Modal -->
<div class="modal fade" id="adicionarModal" tabindex="-1" role="dialog" aria-labelledby="adicionarModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="adicionarModalLabel">Adicionar Artigo</h4>
            </div>

        </div>
    </div>
</div>